/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Account
         * @description Create a new account with zero balance.
         */
        post: operations["register_account_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email (sent as `username`) and password, and get an access token.
         */
        post: operations["login_accounts_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Account
         * @description Get the current account: name, email, plate and balance.
         */
        get: operations["read_my_account_accounts_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Account
         * @description Find an account by its plate, to confirm who receives a transfer or joins a group charge.
         */
        get: operations["lookup_account_accounts_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Balance
         * @description Get the current account balance.
         */
        get: operations["read_balance_accounts_me_balance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Transaction History
         * @description List the transactions sent or received by the current account, newest first.
         */
        get: operations["read_transaction_history_accounts_me_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/reloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Reload
         * @description Reload balance into the current account.
         */
        post: operations["create_reload_transactions_reloads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Transfer
         * @description Transfer balance from the current account to another account.
         */
        post: operations["create_transfer_transactions_transfers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register Group Charge
         * @description Create a group charge. The total is split equally into one member charge per member.
         */
        post: operations["register_group_charge_group_charges_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-charges/created": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Created Group Charges
         * @description List the group charges created by the current account, newest first, with who has paid.
         */
        get: operations["read_created_group_charges_group_charges_created_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-charges/{group_charge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Group Charge
         * @description Get a group charge with its member charges. Only visible to its creator and members.
         */
        get: operations["read_group_charge_group_charges__group_charge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-charges/member-charges/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Member Charges
         * @description List the member charges assigned to the current account, optionally filtered by state.
         */
        get: operations["read_my_member_charges_group_charges_member_charges_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/group-charges/member-charges/{member_charge_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pay My Member Charge
         * @description Pay a member charge of the current account. The money goes to the group charge creator.
         */
        post: operations["pay_my_member_charge_group_charges_member_charges__member_charge_id__pay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Health check endpoint.
         */
        get: operations["root_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /** Owner Name */
            owner_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description La contraseña debe tener al menos 8 caracteres
             */
            password: string;
        };
        /**
         * AccountPublic
         * @description What other people can see of an account: never the email or the balance.
         */
        AccountPublic: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Owner Name */
            owner_name: string;
            /** Plate */
            plate: string;
        };
        /**
         * AccountResponse
         * @description Private data of the current account.
         */
        AccountResponse: {
            /** Owner Name */
            owner_name: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Plate */
            plate: string;
            /** Balance */
            balance: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** BalanceResponse */
        BalanceResponse: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Balance */
            balance: number;
        };
        /** Body_login_accounts_login_post */
        Body_login_accounts_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * ChargeState
         * @enum {string}
         */
        ChargeState: "COMPLETED" | "PENDING";
        /** GroupChargeCreate */
        GroupChargeCreate: {
            /** Name */
            name: string;
            /**
             * Total Amount
             * @description Monto total en pesos colombianos enteros
             */
            total_amount: number;
            /**
             * Member Account Ids
             * @description Cuentas entre las que se divide el total en partes iguales
             */
            member_account_ids: string[];
        };
        /** GroupChargeResponse */
        GroupChargeResponse: {
            /** Name */
            name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Total Amount */
            total_amount: number;
            state: components["schemas"]["ChargeState"];
            creator: components["schemas"]["AccountPublic"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Member Charges
             * @default []
             */
            member_charges: components["schemas"]["MemberChargeResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MemberChargeGroup
         * @description The group charge a member charge belongs to: what the court is and who to pay.
         */
        MemberChargeGroup: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Total Amount */
            total_amount: number;
            state: components["schemas"]["ChargeState"];
            creator: components["schemas"]["AccountPublic"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MemberChargeResponse
         * @description A member charge as shown inside its group charge.
         */
        MemberChargeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            account: components["schemas"]["AccountPublic"];
            /** Assigned Amount */
            assigned_amount: number;
            state: components["schemas"]["ChargeState"];
            /** Paid At */
            paid_at?: string | null;
            /** Transaction Id */
            transaction_id?: string | null;
        };
        /**
         * MyMemberChargeResponse
         * @description A member charge as shown to the member who has to pay it.
         */
        MyMemberChargeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            account: components["schemas"]["AccountPublic"];
            /** Assigned Amount */
            assigned_amount: number;
            state: components["schemas"]["ChargeState"];
            /** Paid At */
            paid_at?: string | null;
            /** Transaction Id */
            transaction_id?: string | null;
            group_charge: components["schemas"]["MemberChargeGroup"];
        };
        /** ReloadCreate */
        ReloadCreate: {
            /**
             * Amount
             * @description Monto de la recarga en pesos colombianos enteros
             */
            amount: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TransactionCreate */
        TransactionCreate: {
            /**
             * To Account Id
             * Format: uuid
             */
            to_account_id: string;
            /**
             * Amount
             * @description Monto a transferir en pesos colombianos enteros
             */
            amount: number;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["TransactionType"];
            /** Amount */
            amount: number;
            from_account?: components["schemas"]["AccountPublic"] | null;
            to_account?: components["schemas"]["AccountPublic"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TransactionType
         * @enum {string}
         */
        TransactionType: "RELOAD" | "DIRECT_TRANSFER" | "COURT_PAYMENT";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_account_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_accounts_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_accounts_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_account_accounts_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    lookup_account_accounts_lookup_get: {
        parameters: {
            query: {
                /** @description Placa de la cuenta, por ejemplo KQX482 o kqx-482 */
                plate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_balance_accounts_me_balance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
        };
    };
    read_transaction_history_accounts_me_transactions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_reload_transactions_reloads_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReloadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transfer_transactions_transfers_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_group_charge_group_charges_post: {
        parameters: {
            query?: never;
            header?: {
                "idempotency-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroupChargeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupChargeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_created_group_charges_group_charges_created_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["ChargeState"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupChargeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_group_charge_group_charges__group_charge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_charge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupChargeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_my_member_charges_group_charges_member_charges_me_get: {
        parameters: {
            query?: {
                state?: components["schemas"]["ChargeState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyMemberChargeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pay_my_member_charge_group_charges_member_charges__member_charge_id__pay_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_charge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyMemberChargeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
